{
 "title": "My realdashboard2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mc_players_total", "legendFormat": "Unique" },
    {
     "expr": "sum(mc_players_online_total) by (world)",
     "legendFormat": "Online ({{world}})"
    },
    { "expr": "mc_whitelisted_players", "legendFormat": "Whitelisted" }
   ]
  },
  {
   "title": "Players Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mc_players_online_total)" }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type='allocated'} - scalar(mc_jvm_memory{type='free'})"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mc_tps" }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mc_loaded_chunks_total", "legendFormat": "{{world}}" }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "mc_jvm_memory{type='max'}", "legendFormat": "Allocated" },
    {
     "expr": "mc_jvm_memory{type='allocated'} -  scalar(mc_jvm_memory{type='free'})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (mc_entities_total) by (world)",
     "legendFormat": "{{world}}_total"
    }
   ]
  },
  {
   "title": "Tickrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "mc_tps", "legendFormat": "TPS" }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "expr": "sum(mc_jvm_threads_current)", "legendFormat": "TOTAL" },
    {
     "expr": "sum by (state) (mc_jvm_threads_state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Unique Players",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    { "expr": "mc_players_total", "legendFormat": "unique players" }
   ]
  },
  {
   "title": "Entity",
   "type": "stat",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum (mc_entities_total) by (type))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}